name: Compile and Update Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install LaTeX and dependencies
        run: sudo apt-get update && sudo apt-get install -y latexmk texlive

      - name: Pull latest changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main

      - name: Watch in which directory we are
        run: pwd

      - name: Change to workflows directory
        run: cd Prova-Action-per-Pages/.github/workflows

      - name: Run main.py script
        run: python main.py

      - name: Return to root directory and push changes
        run: |
          cd Prova-Action-per-Pages
          git add .
          git commit -m "Automated update from GitHub Actions"
          git push origin main
